version: "3.8"
services:
  web:
    build: .
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      api_app:
        aliases:
            - web
        ipv4_address: 172.16.222.2
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      api_app:
        aliases:
            - database
        ipv4_address: 172.16.222.3
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:

networks:
  api_app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.222.0/24